baseURL = "https://bernardobordadagua.com/"
languageCode = "en-us"
title = "Bernardo Borda d'Água"
theme = "hello-friend-ng"
paginate = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

[[params.social]]
name = "twitter"
url = "https://twitter.com/bernardo_agua/"

[[params.social]]
name = "email"
url = "mailto:berna.agua@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/Zizico2/"

[[params.social]]
name = "gitlab"
url = "https://gitlab.com/Zizico2/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bernardo-agua/"


# Subtitle for home
homeSubtitle = "A simple and beautiful blog"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "Do you want to learn about me? Are you curious about the projects I've been involved in? This is my personal website, come take a look. I also write random blog posts!"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "Bernardo Borda d'Água"
subtitle = "A simple theme for Hugo"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "Bernardo Borda d'Água"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
#[[menu.main]]
#identifier = "blog"
#name = "Blog"
#url = "/posts"
